config/routes.rb
Rails.application.routes.draw do
  get "tournoi/index"
  get "home/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  Rails.application.routes.draw do
  get "home/index"
    root "home#index"
    post "populate", to: "home#populate", as: "populate_home_index" # creation des 8 équipes avec 11 joueurs chacune
    post "tournament", to: "home#tournament", as: :tournament
    post "translate", to: "translate#translate"
    resources :teams
    resources :players
  end
end

app/models/player.rb
class Player < ApplicationRecord
  # a une equipe (optionnelle)
  belongs_to :team, optional: true
  # a un role
  belongs_to :role
  # nom obligatoire, unique, max 50 caracteres, lettres, chiffres et espaces
  validates :name, presence: true, length: { maximum: 50 }
  validates :name, uniqueness: true
  validates :name, format: { with: /\A[a-zA-Z0-9\s]+\z/, message: "ne peut contenir que des lettres, chiffres et espaces" }
  # ne peux pas avoir plus de 11 joueurs
  validate :team_player_limit

  private

def team_player_limit
  return unless team # si il n'y a pas d'equipe associee , pas besoin d'aller plus loin

  max_count = 11
  players_count = team.players.where.not(id: self.id).count # compte en excluant le joueur actuel

  if players_count >= max_count
    errors.add(:team, "ne peut pas avoir plus de #{max_count} joueurs")
  end
end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
    before_action :set_player, only: [ :show, :edit, :update, :destroy ]
    before_action :load_roles_and_teams, only: [ :show, :edit, :new, :create ]

    # affichage de la liste des équipes
    def index
        @players = Player.all
    end

    # affichage du formulaire de creation d'un joueur
    def new
        @player = Player.new
    end

    # creation d'un joueur
    def create
        @player = Player.new(player_params)
        if @player.save
            redirect_to @player, notice: "Joueur créé avec succès."
        else
            render :new
        end
    end

    # affichage d'un joueur (redirection automatique vers la page d'édition)
    def show
        render :edit
    end


    # affichage du formulaire d'edition
    def edit
    end

    # mise à jour
    def update
        if @player.update(player_params)
            redirect_to @player, notice: "Joueur mis à jour avec succès."
        else
            redirect_to edit_player_path(@player), alert: "Erreur lors de la mise à jour du joueur."
        end
    end

    # suppression d'un joueur'
    def destroy
        @player.destroy
        redirect_to players_path, notice: "Le joueur a bien été supprimé."
    end

    private

    # before action
    def set_player
        @player = Player.find(params[:id])
    end

    # before action
    def load_roles_and_teams
        @roles = Role.all
        @teams = Team.all
    end

    # n'autoriser que les parametres name et role_id (securite)
    def player_params
        params.require(:player).permit(:name, :role_id, :team_id)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/edit.html.erb
<h1 data-i18n="players-modify_player">Modification joueur</h1>

<%= form_with model: @player, url: player_path(@player), method: :patch do |form| %>
  <div>
    <%= form.label :name, "Nom", data: { i18n: "general-name" } %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :role_id, "Rôle", data: { i18n: "players-role" }%><br>
    <%= form.collection_select :role_id, @roles, :id, :name %>
  </div>

  <div>
    <%= form.label :team_id, "Equipe", data: { i18n: "players-team" } %><br>
    <%= form.collection_select :team_id, @teams, :id, :name, include_blank: "Aucune équipe" %>
  </div>
  <hr/>
  <div class="d-flex justify-content-center">
    <%= form.submit "Modifier", data: { i18n: "general-modify" } %>
<% end %>

app/views/players/index.html.erb
<h1><i class="fas fa-user me-2"></i> <span data-i18n="general-players">Joueurs</span></h1>
<hr/>
<div class="d-flex justify-content-end ">    
    <div class="border-end d-flex align-items-center px-2">
        <span>
            <%= @players.count %> <span data-i18n="lists-elements">Elements</span>
        </span>
    </div>
    <div class="d-flex align-items-center px-2">
        <%= link_to new_player_path, class: "btn btn-success m-1 p-1" do %>
            <span data-i18n="lists-create">Créer</span> <i class="fa-solid fa-plus"></i>
        <% end %>
    </div>
</div>
<div>
    <table class="table table-striped table-hover shadow p-3 border my-2 mx-0">
        <thead>
            <tr>
            <th></th>
            <th data-i18n="players-name">Nom</th>
            <th data-i18n="players-role">Rôle</th>
            <th data-i18n="players-team">Equipe</th>
            <th data-i18n="lists-actions" class="text-end">Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @players.each_with_index do |player, index| %>
            <tr>
                <td><%= index + 1 %></td>
                <td><%= player.name %></td>
                <td><%= player.role.name %></td>
                <td>
                    <% if player.team.present? %>
                        <span class="badge bg-warning text-dark"><%= player.team.name %></span>
                    <% else %>
                        <span class="text-muted">...</span>
                    <% end %>
                </td>
                <td class="d-flex gap-1 justify-content-end">
                    <%= button_to player_path(player), method: :delete, onclick: "return confirm('Êtes-vous sûr ?');", class: "btn btn-danger btn-sm" do %>
                    <i class="fa-solid fa-trash"></i>
                    <% end %>
                    <%= link_to edit_player_path(player), class: "btn btn-primary btn-sm" do %>
                        <i class="fa-solid fa-pen-to-square"></i>
                    <% end %>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/players/new.html.erb
<h1 data-i18n="players-new_player">Nouveau joueur</h1>

<%= form_with model: @player, url: players_path do |form| %>
  <div>
    <%= form.label :name, "Nom", data: { i18n: "general-name" } %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :role_id, "Rôle", data: { i18n: "players-role" }%><br>
    <%= form.collection_select :role_id, @roles, :id, :name %>
  </div>

  <div>
    <%= form.label :team_id, "Equipe", data: { i18n: "players-team" } %><br>
    <%= form.collection_select :team_id, @teams, :id, :name, include_blank: "Aucune équipe" %>
  </div>
  <hr/>
  <div class="d-flex justify-content-center">
    <%= form.submit "Modifier", data: { i18n: "general-modify" } %>
<% end %>

app/views/players/show.html.erb
<h1><span data-i18n="players-player">Joueur</span> : <strong><%= @player.name %></strong></h1>
<p class="card-text">
  <strong data-i18n="players-role">Rôle</strong>
  <%= @player.role.name %>
</p>
<p class="card-text">
  <strong data-i18n="players-team">Équipe</strong>
  <%= @player.team ? @player.team.name : "Aucune équipe" %>
</p>