config/routes.rb
Rails.application.routes.draw do
  get "tournoi/index"
  get "home/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  Rails.application.routes.draw do
  get "home/index"
    root "home#index"
    post "populate", to: "home#populate", as: "populate_home_index" # creation des 8 équipes avec 11 joueurs chacune
    post "tournament", to: "home#tournament", as: :tournament
    post "translate", to: "translate#translate"
    resources :teams
    resources :players
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Probesys" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    
    <%# securite %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# contenu supplementaire eventuel %>
    <%= yield :head %>

    <%# pour faire une application mobile (ignorer) %>
    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <%# icones %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# tous les styles dans app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>

    <%# Bootstrap %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <%# Font Awesome %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flag-icons@7/css/flag-icons.min.css">

  </head>
<script> // GESTION DES COOKIES
  function setCookie(name, value, days) {
    let expires = "";
    if (days) {
      const date = new Date();
      date.setTime(date.getTime() + (days*24*60*60*1000));
      expires = "; expires=" + date.toUTCString();
    }
    document.cookie = name + "=" + (value || "")  + expires + "; path=/";
  }
  function getCookie(name) {
    const nameEQ = name + "=";
    const ca = document.cookie.split(';');
    for(let i=0;i < ca.length;i++) {
      let c = ca[i];
      while (c.charAt(0)==' ') c = c.substring(1,c.length);
      if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length,c.length);
    }
    return null;
  }
</script>
<body>
  
  <div class="container-fluid">
    <div class="row">
      <nav class="navbar navbar-expand-lg border-bottom border-primary shadow">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Test Probesys</a>
        </div>
      </nav>
    </div>

    <div class="row">
      <div class="col-auto border-end p-0 m-0 shadow" style="height: calc(100vh - 56px);">
        <div class="p-3">
          <h4 class="d-none d-sm-inline-block" data-i18n="general-menu">Menu</h4>
          <ul class="nav flex-column">
            <li class="nav-item">
              <%= link_to root_path, class: "nav-link active p-0 mx-0 my-2" do %>
                <i class="fas fa-home me-2"></i> <span class="d-none d-sm-inline-block" data-i18n="general-home">Accueil</span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to teams_path, class: "nav-link active p-0 mx-0 my-2" do %>
                <i class="fas fa-users me-2"></i> <span class="d-none d-sm-inline-block" data-i18n="general-teams">Equipes</span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to players_path, class: "nav-link active p-0 mx-0 my-2" do %>
                <i class="fas fa-user me-2"></i> <span class="d-none d-sm-inline-block" data-i18n="general-players">Joueurs</span>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

      <div class="col p-2">
        <div class="row p-2 m-0 d-flex justify-content-center">
          <div class="col-12 col-md-10 col-lg-8 col-xl-6 card shadow p-3">
              <% if alert %>
                  <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <i class="fa-solid fa-triangle-exclamation"></i> <%= alert %>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                  </div>
              <% end %>
              <% if notice %>
                  <div class="alert alert-primary alert-dismissible fade show" role="alert">
                    <i class="fa-solid fa-circle-info"></i> <%= notice %>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                  </div>
              <% end %>
              <%= yield %>
          </div>
        </div>  
      </div>
    </div>
  </div>

    <%# options flottantes %>
    <div class="position-fixed bottom-0 end-0 m-2 p-1
                bg-dark shadow
                border border-white text-light rounded-3 
                row">
      <div class=" col-3 d-flex justify-content-center align-items-center">
        <i class="fa-solid fa-gear"></i>
      </div>
      <div class=" col-9 p-0 text-center d-flex justify-content-center align-items-center flex-column">
        <div class="form-check form-switch border-bottom border-light">
          <label class="form-check-label" for="darkModeSwitch"><i class="fa-solid fa-moon"></i></label>
          <input class="form-check-input" type="checkbox" role="switch" id="darkModeSwitch" onchange="toggleDarkMode(this.checked)">
        </div>
        <div class="btn-group-horizontal d-flex flex-row my-1" role="group">
          <input type="radio" class="btn-check" name="vbtn-radio" id="vbtn-fr" autocomplete="off" checked>
          <label class="btn btn-sm btn-outline-light py-0 px-1" for="vbtn-fr"><span class="fi fi-fr"></span> <!-- France --></label>
          <input type="radio" class="btn-check" name="vbtn-radio" id="vbtn-uk" autocomplete="off">
          <label class="btn btn-sm btn-outline-light py-0 px-1" for="vbtn-uk"><span class="fi fi-gb"></span> <!-- Royaume-Uni --></label>
        </div>
      </div>
    </div>


<script> // DARK MODE
  function toggleDarkMode(on) {
    if (on) {
      document.documentElement.setAttribute('data-bs-theme', 'dark');
      setCookie('darkMode', '1', 365);
    } else {
      document.documentElement.setAttribute('data-bs-theme', 'light');
      setCookie('darkMode', '0', 365);
    }
  }

  document.addEventListener('DOMContentLoaded', function() {
    const switchInput = document.getElementById('darkModeSwitch');
    switchInput.addEventListener('change', function() {
      toggleDarkMode(this.checked);
    });

    const darkModeCookie = getCookie('darkMode');
    if (darkModeCookie === '1') {
      switchInput.checked = true;
    } else {
      switchInput.checked = false;
    }
    toggleDarkMode(switchInput.checked);

  });
</script>

<script> // traduction FR / UK (i18n)
  function translateI18nStrings(countryCode) {
    const elements = document.querySelectorAll('[data-i18n]');
    const i18nStrings = Array.from(elements).map(element => element.getAttribute('data-i18n'));

    fetch('/translate', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').content
      },
      body: JSON.stringify({
        countryCode: countryCode,
        strings: i18nStrings
      })
    })
    .then(response => {
      if (!response.ok) {
        throw new Error('Network response was not ok');
      }
      return response.json();
    })
    .then(data => {

      // mise a jour des elements html
      elements.forEach(element => {
        const key = element.getAttribute('data-i18n');
        if (data[key]) {
          if (element.tagName === 'INPUT' && element.type === 'submit') {
            element.value = data[key];
          } else {
            element.textContent = data[key];
          }
        } else {
          console.log(`⚠️ i18n: key | '${key}' not found in translations.`);
        }
      });
    })
    .catch(error => console.error('Error:', error));
  }

  function getI18nCookie() {
  return getCookie('i18n') || 'FR'; // Par défaut, FR
}

// Fonction pour déclencher la traduction en fonction du code de pays
function updateTranslationsBasedOnCookie() {
  
}

document.addEventListener('DOMContentLoaded', function() {
  const translationButtons = document.querySelectorAll('input[name="vbtn-radio"]');

  // selection selon cookie
  translationButtons.forEach(button => {
    if (button.id === `vbtn-${getI18nCookie().toLowerCase()}`) {
      button.checked = true;
    }
  });

  // on change traduction
  translationButtons.forEach(button => {
    button.addEventListener('change', function() {
      if (this.checked) {
        setCookie(
          'i18n', 
          this.id.split('-')[1].toUpperCase(),
          365
        );
        translateI18nStrings(getI18nCookie());
      }
    });
  });

  // traduction initiale
  translateI18nStrings(getI18nCookie());
});

</script>
</body>
</html>